In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('../')
import numpy as np
from nips.environment.environment import TestEnvironment
from explauto.environment.context_environment import ContextEnvironment


In [17]:
env_cls = TestEnvironment

env_conf = dict(m_mins=[-1.]*32, 
                m_maxs=[1.]*32, 
                s_mins=[-1.]*110, 
                s_maxs=[1.]*110)


context_mode = dict(mode='mcs',
                    context_n_dims=2,
                    context_sensory_bounds=[[-1., -1.],[1., 1.]])


environment = ContextEnvironment(env_cls, env_conf, context_mode)



In [23]:
m = 2. * np.random.random(32) - 1.

cs = environment.update(m) 

current_context = cs[:2]
s_hand = cs[2:32]
s_joystick = cs[32:52]
s_ergo = cs[52:72]
s_ball = cs[72:92]
s_light = cs[92:102]
s_sound = cs[102:112]

print "current_context", current_context
print "s_hand", s_hand
print "s_joystick", s_joystick
print "s_ergo", s_ergo
print "s_ball", s_ball
print "s_light", s_light
print "s_sound", s_sound

m_dyn [[-0.07734496  0.11632151 -0.15093901 -0.16655548]
 [-0.12801221  0.20856645 -0.24041665 -0.29967436]
 [-0.02080669  0.29941217 -0.03008501 -0.52885359]
 [ 0.08699821  0.37461741  0.18757839 -0.72639076]
 [ 0.15310702  0.42810872  0.33369612 -0.85921004]
 [ 0.09508692  0.34886882  0.27739608 -0.77520099]
 [-0.02471604  0.20891492  0.11900648 -0.58504581]
 [-0.12167348  0.11042992 -0.00768062 -0.44138597]
 [-0.21087364  0.04556089 -0.18496603 -0.3401132 ]
 [-0.30425354  0.0048975  -0.46464772 -0.27242554]
 [-0.37725162 -0.01645271 -0.67599981 -0.22662308]
 [-0.40963992 -0.026724   -0.7524613  -0.22085315]
 [-0.34065355 -0.03872672 -0.5107287  -0.31850289]
 [-0.27756855 -0.04100588 -0.28039318 -0.4092688 ]
 [-0.26094265 -0.02613174 -0.1417903  -0.47874824]
 [-0.43425447  0.05077457 -0.25375894 -0.54779201]
 [-0.6396293   0.13855668 -0.4255808  -0.60484594]
 [-0.79535901  0.20851645 -0.55486873 -0.64608168]
 [-0.91964432  0.24546494 -0.64036645 -0.68505741]
 [-1.          0.25994678

In [24]:
environment.get_current_context()

[4.8441204326546075, -6.5121134767486293]